### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Imna1975** [Vae2009/ConRO_DemonHunter#1]
the error occurs when entering instances  

3x Usage: local configID = C_ClassTalents.GetLastSelectedSavedConfigID(specID)
[string "=[C]"]: in function `GetLastSelectedSavedConfigID'
[string "@ConRO/helper.lua"]:21: in function `CheckTalents'
[string "@ConRO/core.lua"]:2050: in function `EnableRotation'
[string "@ConRO/core.lua"]:2260: in function `?'
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:119: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:29: in function <...ack/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:25>
[string "@BugSack/Libs/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by Vae2009** [comment]
I hope ConRO v10.0.16 will fix this issue
